# Site settings
title: Matt Ramsey
name: Matt Ramsey

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: LinkedIn
   url: https://www.linkedin.com/in/matt-ramsey-89a2a5145

#Any buzzword skills you want to include
skills:
- Microsoft Azure
- Microsoft 365
- Managing ERP systems
- VMWare
- ESXi/Vcenter
- Active Directory
- Group Policy
- Automation
- Cisco Meraki
- Linux
- Project management
- Excellent communication skills
- Complex problem-solver

#Work experience is required
roles:
 - title: System Administrator
   start: 2019
   end: Ongoing
   employer: City Mattress
   description: Responsible for the maintenance, configuration, and reliable operation of computer systems, network servers, and virtualization. Install and upgrade computer components and software, manage virtual servers, and integrate automation processes. Troubleshoot hardware and software errors by running diagnostics, documenting problems and resolutions, prioritizing problems, and assessing impact of issues. Manage two internally hosted ERP systems (Storis and OHM). Administer Microsoft Azure system and Microsoft Azure AD users/roles. Implement and manage internal and revenue generating projects. Tier 3 Service Desk escalations.
 - title: Senior Data Recovery Engineer
   start: 2018
   end: 2019
   employer: CPR Tools Inc.
   description: Secret security clearance obtained. Perform data recoveries on various types of media including hard drives, phones, thumb drives, etc. Preserve and analyze data from electronic data sources and systems. Process collected data and conduct defensible data acquisitions through forensic analysis. Design and develop new techniques and prototypes for use in data recovery and security fields. Train internal and external data recovery technicians.
 - title: Remote Support Technician
   start: 2016
   end: 2018
   employer: The Client Server, Inc.
   description: Tier 1 and Tier 2 ticket work, Email account creation and troubleshooting, Phone setup and troubleshooting, Client workstation and network monitoring, Client ticket follow-ups, Workstation/Server backups, Active Directory management, Printer setup and troubleshooting, Network setup and troubleshooting,
 
#Education is required
education:
 - level: Bachelor of Science (B.Sc.)
   date: 2019
   subject: Information System Management
   school: Florida Gulf Coast University

#List of interesting Github repo/projects to include - optional
Projects/Achievements:
 - PrinterNightmare Patch

intro: |
 Hardworking IT professional with a strong growth mindset. <br/><br/>
 Detail oriented and results-driven employee who is passionate about leading teams and improving processes.<br/><br/>
 An individual who leads by example with a track record of inspiring great customer service and completing projects/tasks before their deadlines.

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>Scala</strong>: My current role uses Scala as the primary language and have been building applications in Scala for the last two years. I am familiar with a range of Scala libraries, such as <a target="_blank" href="https://automateddeveloper.blogspot.com/2017/12/an-opinionated-guide-to-building-apis.html"> Akka-Http for building microservices</a> and <a target="_blank" href="https://automateddeveloper.blogspot.com/2018/09/generic-programming-with-scala.html"> Shapeless for generic programming</a>, as well as familiar with a range of <a target="_blank" href="https://basementcrowd.com/2018/11/28/scala-the-aux-pattern-path-dependent-types/" >functional programming techniques available</a>.<br/><br/>
   <strong>Java</strong>: I am experienced in a variety of Java API’s and frameworks. I have worked with Spring 4, Spring Boot, JPA (Hibernate and EclipseLink) in addition to others. <br/><br/>
   <strong>Groovy</strong> I have used Groovy as a language in production for ~4 years and I am familiar with many of the languages features (such as writing <a target='_blank' href="https://dzone.com/articles/functional-programming-groovy">Functional Programming style groovy</a>) and quirks (such as <a target="_blank" href="https://dzone.com/articles/groovy-retrospective-an-addendum-memory-usage-perm">memory leak issues</a>). <br/><br/>
   <strong>Cloud platforms</strong>: I have primarily used AWS for running production apps on the cloud. I have experience setting up, configuring and running applications using a range of AWS offerings, including EC2, RDS, S3, Cogito, <a target="_blank" href="https://automateddeveloper.blogspot.com/2018/05/serverless-with-aws-lambda-scala.html">Lambda</a> and its more recent <a target="_blank" href="https://automateddeveloper.blogspot.com/2018/10/machine-learning-with-aws-scala.html">Machine Learning capabilities</a>.<br/><br/>
   <strong>Web Development</strong>: Through building web applications, I have also worked with various client side technology, having used jQuery, Bootstrap, LESS, SASS, Backbone/Underscore/Require. More recently I have written React applications (primarily using the Create React App framework, and extending them)<br/><br/>
   <strong>Development Control</strong>: I have a good knowledge of application life-cycle management and have worked with SVN, Git, Maven, Gradle, Sonar, Jenkins, TeamCity, etc. I have experience with an array of testing tools and technologies.<br/><br/>
   I have also gained experience and knowledge of other technologies from several side projects and research that I have undertaken in my free time, including Android, a variety of social APIs (Twitter etc) and cloud platforms such as CloudFoundry/OpenShift/AppFog/AWS. <br/><br/>
   As part of Nerdability, I created, and am now primary contributor to, two Spring projects - <a target='_blank' href="https://github.com/robhinds/spring-social-geeklist">Spring-Social-Geeklist</a> and <a target='_blank' href="https://github.com/nerdability/spring-social-khan-academy">Spring-Social-Khan-Academy</a>, which provide core integration with those third-party APIs on top of the Spring Social framework. They are both listed as community projects: <a target='_blank' href="https://projects.spring.io/spring-social/">https://projects.spring.io/spring-social/</a>. <br/><br/>
   I write a blog covering technical and opinion articles that can be found here: <a target='_blank' href="https://automateddeveloper.blogspot.com/">automateddeveloper.blogspot.com</a> (I am also a <a target='_blank' href="https://dzone.com/users/899489/rhinds.html">DZone MVB</a>)
