# Site settings
title: Matt Ramsey
name: Matt Ramsey

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: LinkedIn
   url: https://www.linkedin.com/in/matt-ramsey-89a2a5145

#Any buzzword skills you want to include
skills:
- Microsoft Azure
- Microsoft 365
- Managing ERP systems
- VMWare
- ESXi/Vcenter
- Active Directory
- Group Policy
- Automation
- Cisco Meraki
- Linux
- Project management
- Excellent communication skills
- Complex problem-solver

#Work experience is required
roles:
 - title: System Administrator
   start: 2019
   end: Ongoing
   employer: City Mattress
   description: Responsible for the maintenance, configuration, and reliable operation of computer systems, network servers, and virtualization. Install and upgrade computer components and software, manage virtual servers, and integrate automation processes. Troubleshoot hardware and software errors by running diagnostics, documenting problems and resolutions, prioritizing problems, and assessing impact of issues. Manage two internally hosted ERP systems (Storis and OHM). Administer Microsoft Azure system and Microsoft Azure AD users/roles. Implement and manage internal and revenue generating projects. Tier 3 Service Desk escalations.
 - title: Senior Data Recovery Engineer
   start: 2018
   end: 2019
   employer: CPR Tools Inc.
   description: Secret security clearance obtained. Perform data recoveries on various types of media including hard drives, phones, thumb drives, etc. Preserve and analyze data from electronic data sources and systems. Process collected data and conduct defensible data acquisitions through forensic analysis. Design and develop new techniques and prototypes for use in data recovery and security fields. Train internal and external data recovery technicians.
 - title: Remote Support Technician
   start: 2016
   end: 2018
   employer: The Client Server, Inc.
   description: Tier 1 and Tier 2 ticket work, Email account creation and troubleshooting, Phone setup and troubleshooting, Client workstation and network monitoring, Client ticket follow-ups, Workstation/Server backups, Active Directory management, Printer setup and troubleshooting, Network setup and troubleshooting,
 
#Education is required
education:
 - level: Bachelor of Science (B.Sc.)
   date: 2019
   subject: Information System Management
   school: Florida Gulf Coast University

#List of interesting Github repo/projects to include - optional
Projects/Achievements:
 - PrinterNightmare Patch

intro: |
 Hardworking IT professional with a strong growth mindset. <br/><br/>
 Detail oriented and results-driven employee who is passionate about leading teams and improving processes.<br/><br/>
 An individual who leads by example with a track record of inspiring great customer service and completing projects/tasks before their deadlines.
